/**
 * Extracts recipe information from the generated text using AI refinement
 * @param {string} generatedText - The text generated by the model
 * @returns {Object} An object containing the recipe name, ingredients, and instructions
 * @throws {Error} If the text cannot be parsed into the required format
 */
export async function parseRecipe(generatedText) {
  // Find and parse JSON structure
  const jsonMatch = generatedText.match(/\{[\s\S]*\}/);
  if (!jsonMatch) {
    return {
      name: "Vietnamese Recipe",
      ingredients: "Could not generate ingredients. Please try again.",
      instructions: "Could not generate instructions. Please try again.",
    };
  }

  try {
    const parsed = JSON.parse(jsonMatch[0]);

    // Validate the structure
    if (!parsed.name || typeof parsed.name !== "string") {
      throw new Error("Invalid or missing recipe name");
    }

    if (!Array.isArray(parsed.ingredients) || parsed.ingredients.length === 0) {
      throw new Error("Invalid or missing ingredients array");
    }

    if (
      !Array.isArray(parsed.instructions) ||
      parsed.instructions.length !== 5
    ) {
      throw new Error("Instructions must be an array with exactly 5 steps");
    }

    // Format the response
    return {
      name: parsed.name.trim(),
      ingredients: parsed.ingredients.join("\n"),
      instructions: parsed.instructions.join("\n"),
    };
  } catch (e) {
    console.log("Failed to parse recipe:", e.message);
    return {
      name: "Vietnamese Recipe",
      ingredients: "Could not parse ingredients. Please try again.",
      instructions: "Could not parse instructions. Please try again.",
    };
  }
}

// Helper function to make API call with retries
async function makeHuggingFaceRequest(prompt, maxRetries = 3) {
  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      console.log(
        `Attempt ${attempt} of ${maxRetries} to call Hugging Face API...`
      );
      const response = await fetch(
        "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.2",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${process.env.HUGGINGFACE_API_KEY}`,
          },
          body: JSON.stringify({
            inputs: prompt,
            parameters: {
              max_length: 1000,
              temperature: 0.3,
              top_p: 0.95,
              do_sample: true,
              num_return_sequences: 1,
              repetition_penalty: 1.2,
              return_full_text: false,
            },
          }),
        }
      );

      if (response.status === 503) {
        console.log("Model is loading, waiting before retry...");
        await delay(20000); // Wait 20 seconds before retrying
        continue;
      }

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || response.statusText);
      }

      return await response.json();
    } catch (error) {
      console.error(`Attempt ${attempt} failed:`, error.message);
      if (attempt === maxRetries) {
        throw error;
      }
      await delay(5000); // Wait 5 seconds between retries
    }
  }
}

// Helper function to delay execution
const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
